{
  description = "TEE email bot: reproducible OCI image for Phala dstack deployment";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.11";
    pyproject-nix = {
      url = "github:pyproject-nix/pyproject.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    uv2nix = {
      url = "github:pyproject-nix/uv2nix";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    pyproject-build-systems = {
      url = "github:pyproject-nix/build-system-pkgs";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.uv2nix.follows = "uv2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { self, nixpkgs, pyproject-nix, uv2nix, pyproject-build-systems, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      lib = nixpkgs.lib;
      python = pkgs.python311;

      workspace = uv2nix.lib.workspace.loadWorkspace {
        workspaceRoot = ./deploy/phala;
      };

      pyprojectOverlay = workspace.mkPyprojectOverlay {
        sourcePreference = "wheel";
      };

      pyprojectOverrides = _final: _prev: { };

      pythonSet =
        (pkgs.callPackage pyproject-nix.build.packages { inherit python; }).overrideScope
          (lib.composeManyExtensions [
            pyproject-build-systems.overlays.default
            pyprojectOverlay
            pyprojectOverrides
          ]);

      venv = pythonSet.mkVirtualEnv "email-bot-env" workspace.deps.default;

      # Generated by `python -m deploy.render_image_manifest`, one file list per
      # role, from the modules that role's entry points actually import. It used
      # to be one list for one shared image (and before that a filter over file
      # extensions, which shipped the co-signer's key derivation into an image
      # that starts none of it). Four lists now, because the four containers run
      # four entry points and a module belongs in a container only if that
      # container starts something that imports it: the receiver Google posts to
      # no longer carries the inference client or the custody stack the mail
      # role's imports drag in, and the proxy carries neither. See that module's
      # docstring.
      imageManifests = import ./deploy/phala/image_files.nix;

      # `images` below is keyed by the names in that file, which is generated
      # from `backend/roles.py`, so the roles this flake builds are the roles
      # that exist rather than a list restated here.
      # `deploy/phala/build_and_publish.sh` reads the same file the same way.

      # One role's source tree: exactly the files its manifest names. Nix store
      # paths are content-addressed, so a file shared by two roles is stored and
      # pulled once across the images rather than duplicated -- the dedup is what
      # makes four images cost the space of one plus each role's own leaves.
      mkAppCode =
        files:
        builtins.path {
          name = "email-bot-app";
          path = ./.;
          filter =
            path: type:
            let
              rel = lib.removePrefix (toString ./. + "/") (toString path);
            in
            if type == "directory" then
              lib.any (f: lib.hasPrefix (rel + "/") f) files
            else
              lib.elem rel files;
        };

      # No crontab and no supercronic. The schedule this file used to restate
      # from deploy/hetzner/*.timer -- two formats, neither able to read the
      # other -- is now `backend/daemons/scheduler.py`, a thread in the mail
      # daemon in both deployments. That deletes the duplicate cadence, and it
      # deletes a process: supercronic started a shell per job, and a shell is a
      # process execguard's seccomp filter was never installed in.

      # The three accounts the enclave's containers run as, and the two groups
      # they share. The names are `backend/paths.py`'s DATA_GROUP and
      # WAKE_GROUP, spelled the same here on purpose: that module resolves them
      # with `grp.getgrnam` and sets every mode from the answer, so baking these
      # names in is what makes one piece of code decide file modes on the
      # Hetzner box and inside the image. Numeric ids are fixed because the
      # `database` and `state` volumes are shared between containers, and a uid
      # is all a shared volume carries.
      accounts = {
        mail = { uid = 10001; groups = [ "letterlock-data" "letterlock-wake" ]; };
        web = { uid = 10002; groups = [ "letterlock-data" ]; };
        hook = { uid = 10003; groups = [ "letterlock-wake" ]; };
        # The egress proxy: in no shared group at all, because it reads no file
        # of ours. It is its own account for the reason it is on the box -- the
        # process holding the network must not be the one holding the API keys.
        egress = { uid = 10004; groups = [ ]; };
        # The ingress forwarder, and the counterpart of the above. It is what
        # lets `web` and `hook` give up their published ports and move onto the
        # internal network alone, which turns the egress allowlist from a
        # setting their own HTTP clients honour into something docker enforces
        # for them. Also in no group: it moves bytes and reads nothing.
        ingress = { uid = 10005; groups = [ ]; };
      };
      sharedGids = { letterlock-data = 10010; letterlock-wake = 10011; };

      # The shell field is /noshell in every row, root's included, and the path
      # does not exist. Nothing reads it -- `grp.getgrnam` and `pwd` want the
      # uid and the group -- but the image ships no shell, and a passwd file
      # promising /bin/sh is a measured file making a false statement about what
      # is in the image.
      passwdFile = pkgs.writeText "passwd" (''
        root:x:0:0:root:/root:/noshell
      '' + lib.concatStrings (lib.mapAttrsToList (name: a: ''
        letterlock-${name}:x:${toString a.uid}:${toString a.uid}::/app:/noshell
      '') accounts));

      groupFile = pkgs.writeText "group" (''
        root:x:0:
      '' + lib.concatStrings (lib.mapAttrsToList (name: a: ''
        letterlock-${name}:x:${toString a.uid}:
      '') accounts) + lib.concatStrings (lib.mapAttrsToList (group: gid: ''
        ${group}:x:${toString gid}:${lib.concatStringsSep "," (
          lib.mapAttrsToList (name: _: "letterlock-${name}") (
            lib.filterAttrs (_: a: lib.elem group a.groups) accounts))}
      '') sharedGids));

      # No entrypoint script. There used to be one shell shared by every image,
      # dispatching on a role name and running the attestation gate as a
      # separate `python -m` before `exec`ing the service. Both halves moved
      # into Python: docker-compose.yml's `command:` names the module directly,
      # and the two data-holding roles call `tee_boot.gate_or_exit()` from their
      # own `__main__` before they open anything.
      #
      # The point is what is left: `python` is pid 1 and the only process, so
      # `execguard.py`'s seccomp filter -- which a process installs in itself
      # and which cannot cover a parent that predates it -- covers the whole
      # container. There is no shell in the image to cover.
      #
      # Which role a container plays is still a `command:` in
      # docker-compose.yml, and that file is hashed into the dstack
      # `compose-hash` extended into RTMR3 -- so which process runs as which
      # account, which image it runs, and which secrets each is handed, is
      # measured rather than merely configured. An operator who moves
      # SESSION_SECRET to the mail container changes the measurement and
      # `cosigner/attest.py` stops accepting the client certificate. What the
      # `case` used to refuse -- an unknown role -- is now refused by there
      # being no name to get wrong: a `command:` either is a module in that
      # role's image or the container does not start.
      #
      # There is deliberately no role that starts everything. That was the shape
      # before this split: four processes, one uid, one environment holding
      # every secret, so a parsing bug in the web server was every mailbox in
      # the enclave. That stopped being the arrangement in `01ba733`; this is
      # the same change, and a shared dispatcher would put it one edit away
      # again -- as well as pulling all five roles' imports into every image,
      # since `deploy/render_image_manifest.py` counts a function-local import
      # exactly like a top-level one.

      # `database` and `state` are named volumes mounted over these paths, shared
      # between containers. Docker seeds a named volume from the first container
      # to mount it, ownership and mode included, so every image that mounts one
      # seeds it identically (mail uid, letterlock-data, setgid) and whichever
      # container starts first the result is the same. Both are setgid, matching
      # paths.DIR_MODE_SHARED / DIR_MODE_TRAVERSABLE: state/ is traversable
      # because the hook uid writes its spool there and is deliberately not in
      # the data group, database/ is not because who has an account is itself
      # worth keeping. The hook role mounts state but not database, so its image
      # seeds only state -- the account store is not in its filesystem at all,
      # and the two network roles mount neither, because they read no file of
      # ours.
      roleVolumes = {
        mail = [ "database" "state" ];
        web = [ "database" "state" ];
        hook = [ "state" ];
        egress = [ ];
        ingress = [ ];
      };
      # The port each role's container listens on. Metadata only -- compose
      # declares the real mapping -- but kept per role so the image states what
      # it listens on. Only `ingress` is published to the host; `web` and `hook`
      # listen on the internal network alone, which is the whole point of that
      # role, and `egress` is reached by container name on the same networks.
      # The mail role listens on nothing (it is reached over the custody socket
      # and the FIFO).
      rolePorts = {
        mail = [ ];
        web = [ "8790" ];
        hook = [ "8787" ];
        egress = [ "8792" ];
        ingress = [ "8790" "8787" ];
      };

      seedVolume = vol: ''
        mkdir -p ./app/${vol}
        chown ${toString accounts.mail.uid}:${toString sharedGids.letterlock-data} ./app/${vol}
        chmod ${if vol == "database" then "2770" else "2771"} ./app/${vol}
      '';

      # One role's image: the interpreter over that role's own code and data.
      # No .gmail-mcp directory in any of them -- it existed to carry
      # gcp-oauth.keys.json, and under TEE_REQUIRED oauth_app refuses that file
      # and the boot gate refuses to start with one present.
      #
      # `contents` is the certificate bundle and nothing else. coreutils and
      # bash were here for the entrypoint script; with that gone, an image with
      # a shell in it is an image holding the one program `execguard.py` exists
      # to stop a payload reaching. Nothing shipped starts a program --
      # tests/test_image_manifest.py proves the absence of subprocess, os.exec*
      # and os.fork across every measured file -- so there is nothing left to
      # need them.
      mkImage =
        role: files:
        pkgs.dockerTools.buildLayeredImage {
          name = "tee-email-bot-${role}";
          tag = "latest";
          contents = [ pkgs.cacert ];
          enableFakechroot = true;
          fakeRootCommands = ''
            mkdir -p ./app ./etc
            cp -R ${mkAppCode files}/. ./app/
            cp ${passwdFile} ./etc/passwd
            cp ${groupFile} ./etc/group
            chmod -R u+w ./app
            chown -R 0:0 ./app
            ${lib.concatMapStrings seedVolume roleVolumes.${role}}
          '';
          config = {
            WorkingDir = "/app";
            # No Entrypoint and no Cmd: docker-compose.yml's `command:` is the
            # whole argv, so the module a container runs is stated in the file
            # whose hash is measured into RTMR3 rather than baked in here where
            # the compose file could not contradict it.
            Entrypoint = [ ];
            ExposedPorts = lib.listToAttrs (
              map (p: lib.nameValuePair "${p}/tcp" { }) rolePorts.${role}
            );
            Env = [
              # The venv alone. `command:` says `python`, and this is what
              # decides which one -- there is no other bin directory in the
              # image to find a different answer in.
              "PATH=${venv}/bin"
              "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt"
              "LANG=C.UTF-8"
              "TZ=UTC"
            ];
          };
        };

      images = builtins.mapAttrs mkImage imageManifests;
    in
    {
      packages.${system} = {
        inherit venv;
        image-mail = images.mail;
        image-web = images.web;
        image-hook = images.hook;
        image-egress = images.egress;
        # `nix build .#images` builds all four; the default is the mail image,
        # the one role that must be present for the enclave to do anything.
        images = pkgs.linkFarm "tee-email-bot-images" (
          lib.mapAttrsToList (role: img: { name = role; path = img; }) images
        );
        default = images.mail;
      };
    };
}
