{
  description = "TEE email bot: reproducible OCI image for Phala dstack deployment";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.11";
    pyproject-nix = {
      url = "github:pyproject-nix/pyproject.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    uv2nix = {
      url = "github:pyproject-nix/uv2nix";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    pyproject-build-systems = {
      url = "github:pyproject-nix/build-system-pkgs";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.uv2nix.follows = "uv2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { self, nixpkgs, pyproject-nix, uv2nix, pyproject-build-systems, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      lib = nixpkgs.lib;
      python = pkgs.python311;

      workspace = uv2nix.lib.workspace.loadWorkspace {
        workspaceRoot = ./deploy/phala;
      };

      pyprojectOverlay = workspace.mkPyprojectOverlay {
        sourcePreference = "wheel";
      };

      pyprojectOverrides = _final: _prev: { };

      pythonSet =
        (pkgs.callPackage pyproject-nix.build.packages { inherit python; }).overrideScope
          (lib.composeManyExtensions [
            pyproject-build-systems.overlays.default
            pyprojectOverlay
            pyprojectOverrides
          ]);

      venv = pythonSet.mkVirtualEnv "email-bot-env" workspace.deps.default;

      # Generated by `python -m deploy.render_image_manifest` from the modules
      # the entry points below actually import. This was a filter over file
      # extensions, which shipped the co-signer's key derivation and the egress
      # proxy into an image that starts neither, and shipped no data file at all
      # because none of them end in .py. See that module's docstring.
      imageFiles = import ./deploy/phala/image_files.nix;

      appCode = builtins.path {
        name = "email-bot-app";
        path = ./.;
        filter =
          path: type:
          let
            rel = lib.removePrefix (toString ./. + "/") (toString path);
          in
          if type == "directory" then
            lib.any (f: lib.hasPrefix (rel + "/") f) imageFiles
          else
            lib.elem rel imageFiles;
      };

      crontab = pkgs.writeText "email-bot-crontab" ''
        0 5 * * * cd /app && python -m backend.drafting.email_summary
        0 4 * * 1 cd /app && python -m backend.onboarding.watch_renew
      '';

      entrypoint = pkgs.writeShellApplication {
        name = "email-bot-entrypoint";
        runtimeInputs = [ venv pkgs.supercronic pkgs.coreutils ];
        text = ''
          cd /app
          mkdir -p /app/.gmail-mcp /app/database
          # Track F3 attest-before-run gate. Under TEE_REQUIRED it fails closed
          # (exit -> Restart=always retries) rather than touching mailboxes
          # without proof the CVM runs the published, attested measurement.
          if ! python -m backend.tee.tee_boot; then
            echo "tee_boot gate failed; refusing to start services" >&2
            exit 1
          fi
          python -m backend.daemons.daemon_loop &
          d=$!
          python -m backend.daemons.gmail_hook_server &
          w=$!
          python -m frontend.web_server &
          ui=$!
          supercronic /app/crontab &
          c=$!
          trap 'kill "$d" "$w" "$ui" "$c" 2>/dev/null || true' TERM INT
          wait -n
          kill "$d" "$w" "$ui" "$c" 2>/dev/null || true
          exit 1
        '';
      };

      image = pkgs.dockerTools.buildLayeredImage {
        name = "tee-email-bot";
        tag = "latest";
        contents = [ pkgs.cacert pkgs.coreutils pkgs.bashInteractive ];
        enableFakechroot = true;
        fakeRootCommands = ''
          mkdir -p ./app
          cp -R ${appCode}/. ./app/
          cp ${crontab} ./app/crontab
          chmod -R u+w ./app
        '';
        config = {
          WorkingDir = "/app";
          Entrypoint = [ "${entrypoint}/bin/email-bot-entrypoint" ];
          ExposedPorts = {
            "8787/tcp" = { };
            "8790/tcp" = { };
          };
          Env = [
            "PATH=${venv}/bin:${pkgs.supercronic}/bin:${pkgs.coreutils}/bin:${pkgs.bashInteractive}/bin"
            "SHELL=${pkgs.bashInteractive}/bin/bash"
            "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt"
            "LANG=C.UTF-8"
            "TZ=UTC"
          ];
        };
      };
    in
    {
      packages.${system} = {
        inherit image venv;
        default = image;
      };
    };
}
