"""Render the egress allowlist from the modules that already name the hosts.

`backend/egress.py` used to derive the list at runtime, which was the right
answer to the right question and put the answer in the wrong process. Every
entry comes from a module that names a host for its own reasons -- adding a
provider must not be able to leave the allowlist behind -- so the module walked
`llm_client.PROVIDERS`, `oauth_app`, `telegram.API_ROOT`, `polar_api`'s two
bases, the TDX allowlists' `pccs_url` and `calendar_public.ICS_ROOT` on every
call.

The cost only appeared once the enclave shipped one image per role. Those
imports are import edges whether they sit at module level or inside a function,
and `tools/reachability.py` counts them the same way for the same reason: a lazy
import still executes. `calendar_public` reaches `account`, which reaches
`custody.keyring`, `custody.client`, `tee_boot`, `secrets_checks` and through it
billing, Telegram and the inference client. So the container holding the only
route off the host carried the custody stack and the inference client in its
filesystem, to compute thirteen strings. The process that holds the network is
deliberately not the process that holds the API keys, and under a per-role image
that has to be true of the filesystem and not only of the uid and the
environment.

So the derivation moves here, to render time, where this repository already
keeps `image_files.nix`, `deploy/phala/pyproject.toml` and the Caddyfile:

    python -m deploy.render_egress_allowlist            # rewrite the file
    python -m deploy.render_egress_allowlist --check    # exit 1 if it is stale

Derived, not typed, is unchanged -- nobody edits the list by hand, and
`tests/test_egress.py` still compares what ships against the live constants, so
a provider added without a re-render fails there. What changed is when the walk
runs and which process has to be able to run it. `backend/egress.py` reads the
committed file and imports nothing but `backend.site`.
"""

import json
import sys
from urllib.parse import urlsplit

from backend import egress, site

# Google's two API hosts are the only entries not read off a constant of ours,
# because there is no constant to read: googleapiclient takes the root URL out
# of the discovery document bundled in the library, so the name lives in a
# vendored JSON blob. `tests/test_egress.py` reads those documents for the
# api/version pairs in `google_client.APIS` and fails if a rootUrl host is
# missing from this tuple.
GOOGLE_API_HOSTS = ("www.googleapis.com", "gmail.googleapis.com")

NOTE = [
    "Every hostname anything on this box may open a connection to.",
    "",
    "Generated by deploy/render_egress_allowlist.py from the modules that",
    "already name each host -- do not edit. Add the provider, the endpoint or",
    "the PCCS pin where it belongs, then re-render:",
    "",
    "    python -m deploy.render_egress_allowlist",
    "",
    "Read by backend/egress.py, which imports nothing else to read it: the",
    "egress proxy is the one process with a route off the host and must not",
    "carry the custody stack or the inference client to find out where it may",
    "connect. Exact matches only, names and no addresses, port 443 only -- see",
    "that module for what the control is and is not.",
]


def _host(url):
    """The hostname in a URL, lowercased. Asserts rather than returning None:
    every caller below passes a constant that is supposed to be an https URL,
    and a silent empty string here would quietly shrink the allowlist."""
    assert url, "cannot take a hostname out of an empty URL"
    host = urlsplit(url).hostname
    assert host, f"no hostname in {url!r}"
    return host.lower()


def _provider_hosts():
    """Inference. Both the completions endpoint and, for a confidential
    provider, the attestation endpoint: refusing the second would fail
    `inference_attestation.require()` and take the provider down just as surely
    as refusing the first."""
    from backend.integrations import llm_client

    hosts = set()
    for provider in llm_client.PROVIDERS.values():
        hosts.add(_host(provider.base_url))
        if provider.attestation_url:
            hosts.add(_host(provider.attestation_url))
    return hosts


def _google_hosts():
    """Consent, token exchange, revocation and the token-info check the Pub/Sub
    webhook runs, plus the two API roots. `oauth_app.TOKEN_ENDPOINT` is
    `cosigner.protocol`'s, which is the same string the co-signer's policy pins
    `htu` against, so one edit moves the allowlist and the policy together.

    `calendar_public.ICS_ROOT` is a different host from the API roots because it
    is a different kind of request: no credentials, the public feed as a stranger
    sees it. It is listed unconditionally rather than behind
    `oauth_app.acl_scope_registered()`, for the reason `_billing_hosts` lists
    both Polar deployments -- the proxy cannot read the app's environment, and an
    allowlist that flips with a toggle breaks the first time the toggle moves."""
    from backend.daemons import gmail_hook_server
    from backend.integrations.gmail_gcal import calendar_public, oauth_app

    return {
        _host(oauth_app.AUTH_ENDPOINT),
        _host(oauth_app.TOKEN_ENDPOINT),
        # The same host as the token endpoint today. Derived rather than left to
        # that coincidence: if Google ever splits them, a deletion that cannot
        # revoke is a grant we told the user we withdrew.
        _host(oauth_app.REVOKE_ENDPOINT),
        _host(gmail_hook_server.CERTS_URL),
        _host(calendar_public.ICS_ROOT),
    } | set(GOOGLE_API_HOSTS)


def _billing_hosts():
    """Both Polar deployments, not whichever one `POLAR_SANDBOX` currently
    selects. The proxy cannot read that flag, they are the same operator, and an
    allowlist that flips with a toggle is one that breaks the first time the
    toggle moves."""
    from backend.billing import polar_api

    return {_host(polar_api.PROD_BASE), _host(polar_api.SANDBOX_BASE)}


def _pccs_hosts():
    """The provisioning certification caching service each quote verifier on this
    machine fetches collateral from. Asked of the allowlist files rather than
    hardcoded, since re-pinning against a different PCCS is a thing those files
    are allowed to do -- and re-pinning is an edit to a committed file, which is
    a commit, which is a re-render.

    Both verifiers are read here and not behind the `find_spec` guard the
    runtime derivation needed. That guard existed because a static import of
    `cosigner.attest` would have dragged the co-signer's allowlist reader into an
    enclave image; this module ships into no image at all, so the question does
    not arise and the rendered list covers both boxes."""
    from backend.integrations import inference_attestation
    from cosigner import attest

    urls = [inference_attestation.policy().get("pccs_url"),
            attest.policy().get("pccs_url")]
    return {_host(url) for url in urls if url}


def _alert_hosts():
    """Telegram. Both trust domains reach it -- the app for a user's summary, the
    co-signer for the one call it keeps into `backend/` -- and both do it through
    this same constant."""
    from backend.integrations import telegram

    return {_host(telegram.API_ROOT)}


def derive():
    """Every hostname, sorted. The one answer the renderer and the tests read,
    so a test cannot pass against a list the proxy does not use."""
    found = set()
    found |= _provider_hosts()
    found |= _google_hosts()
    found |= _billing_hosts()
    found |= _pccs_hosts()
    found |= _alert_hosts()
    found.add(site.COSIGNER_HOST.lower())
    assert all(found), "an empty hostname reached the allowlist"
    assert found, "the allowlist derived to nothing; the constants did not load"
    return sorted(found)


def render():
    return json.dumps({"_comment": NOTE, "hosts": derive()}, indent=2) + "\n"


def main(argv):
    rendered = render()
    if "--check" in argv:
        current = egress.ALLOWLIST_FILE.read_text()
        if current != rendered:
            print(f"{egress.ALLOWLIST_FILE} is stale; run "
                  "python -m deploy.render_egress_allowlist", file=sys.stderr)
            return 1
        return 0
    egress.ALLOWLIST_FILE.write_text(rendered)
    print(f"wrote {egress.ALLOWLIST_FILE} ({len(derive())} hosts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
