"""Render the Caddy site config from backend/site.py.

Caddy cannot import the app's constants, so the config is generated from them
instead of maintained alongside them. deploy/hetzner/Caddyfile is the committed
output; regenerate it whenever a host or port changes:

    python -m deploy.render_caddyfile > deploy/hetzner/Caddyfile

Then install it by hand (deploy.sh deliberately does not touch Caddy):

    scp deploy/hetzner/Caddyfile root@<box>:/tmp/Caddyfile.new
    ssh root@<box> 'caddy validate --adapter caddyfile --config /tmp/Caddyfile.new \
        && install -m 0644 /tmp/Caddyfile.new /etc/caddy/Caddyfile && systemctl reload caddy'
"""

import sys

from backend import site
from cosigner import protocol as cosigner_protocol

HEADER = """\
# Generated by deploy/render_caddyfile.py from backend/site.py -- do not edit here.
# Change a host or port in backend/site.py (or LETTERLOCK_HOST in .env), then:
#   python -m deploy.render_caddyfile > deploy/hetzner/Caddyfile
"""


def co_tenant_handles():
    """Routes for other products sharing this box. This module renders the whole
    Caddy config, so omitting one deletes it; see site.CO_TENANT_ROUTES."""
    blocks = []
    for path, port, owner in site.CO_TENANT_ROUTES:
        blocks.append(
            f"\t# Not Letterlock: {owner}.\n"
            f"\t# Kept because this file is the whole Caddy config, so dropping\n"
            f"\t# the route would take that service offline.\n"
            f"\thandle {path} {{\n"
            f"\t\treverse_proxy {site.upstream(port)}\n"
            f"\t}}"
        )
    return "".join(b + "\n" for b in blocks)


def api_block():
    """The original box: Gmail Pub/Sub push and the Polar webhook. Sign-in lives
    on the app host now; the standalone /onboard flow was retired."""
    return f"""\
{site.API_HOST} {{
\thandle {site.POLAR_WEBHOOK_PATH} {{
\t\treverse_proxy {site.upstream(site.BILLING_WEBHOOK_PORT)}
\t}}
{co_tenant_handles()}\
\t# The catch-all keeps the Gmail Pub/Sub push (POST /) on the webhook. Serving
\t# a landing page from this site root would require repointing the push
\t# subscription off "/" first.
\thandle {{
\t\treverse_proxy {site.upstream(site.GMAIL_PUSH_PORT)}
\t}}
}}"""


def app_block():
    """The product host: web UI on every path, plus the Polar webhook so the
    endpoint can be moved here without touching the Polar dashboard twice."""
    return f"""\
{site.APP_HOST} {{
\thandle {site.POLAR_WEBHOOK_PATH} {{
\t\treverse_proxy {site.upstream(site.BILLING_WEBHOOK_PORT)}
\t}}
{co_tenant_handles()}\
\thandle {{
\t\treverse_proxy {site.upstream(site.WEB_PORT)}
\t}}
}}"""


def cosigner_block():
    """The split-custody co-signer, and the only site that demands a client
    certificate.

    `mode require` asks for one and does not check it against a CA pool: the
    enclave's certificate is RA-TLS, self-signed, and vouched for by the TDX
    quote inside it rather than by an issuer. Caddy cannot judge that, so it
    hands the certificate up as base64 DER and cosigner/attest.py does the five
    checks. A request reaching the loopback port with no such header is a
    bypassed proxy, and the service refuses it.

    TLS-ALPN is disabled for this host because the challenge is a TLS handshake
    Let's Encrypt performs without a client certificate, which `mode require`
    would reject; HTTP-01 still issues the certificate."""
    return f"""\
{site.COSIGNER_HOST} {{
\ttls {{
\t\tclient_auth {{
\t\t\tmode require
\t\t}}
\t\tissuer acme {{
\t\t\tdisable_tlsalpn_challenge
\t\t}}
\t}}
\thandle {{
\t\treverse_proxy {site.upstream(site.COSIGNER_PORT)} {{
\t\t\theader_up {cosigner_protocol.CLIENT_CERT_HEADER} {{http.request.tls.client.certificate_der_base64}}
\t\t}}
\t}}
}}"""


def alias_blocks():
    return [f"{host} {{\n\tredir https://{site.APP_HOST}{{uri}} permanent\n}}"
            for host in site.ALIAS_HOSTS]


def render():
    blocks = [api_block(), app_block(), cosigner_block(), *alias_blocks()]
    return HEADER + "\n" + "\n\n".join(blocks) + "\n"


if __name__ == "__main__":
    sys.stdout.write(render())
