"""Render the Caddy site config from backend/site.py.

Caddy cannot import the app's constants, so the config is generated from them
instead of maintained alongside them. deploy/hetzner/Caddyfile is the committed
output; regenerate it whenever a host or port changes:

    python -m deploy.render_caddyfile > deploy/hetzner/Caddyfile

Then install it by hand (deploy.sh deliberately does not touch Caddy):

    scp deploy/hetzner/Caddyfile root@<box>:/tmp/Caddyfile.new
    ssh root@<box> 'caddy validate --adapter caddyfile --config /tmp/Caddyfile.new \
        && install -m 0644 /tmp/Caddyfile.new /etc/caddy/Caddyfile && systemctl reload caddy'
"""

import sys

from backend import site

HEADER = """\
# Generated by deploy/render_caddyfile.py from backend/site.py -- do not edit here.
# Change a host or port in backend/site.py (or LETTERLOCK_HOST in .env), then:
#   python -m deploy.render_caddyfile > deploy/hetzner/Caddyfile
"""


def co_tenant_handles():
    """Routes for other products sharing this box. This module renders the whole
    Caddy config, so omitting one deletes it; see site.CO_TENANT_ROUTES."""
    blocks = []
    for path, port, owner in site.CO_TENANT_ROUTES:
        blocks.append(
            f"\t# Not Letterlock: {owner}.\n"
            f"\t# Kept because this file is the whole Caddy config, so dropping\n"
            f"\t# the route would take that service offline.\n"
            f"\thandle {path} {{\n"
            f"\t\treverse_proxy 127.0.0.1:{port}\n"
            f"\t}}"
        )
    return "".join(b + "\n" for b in blocks)


def api_block():
    """The original box: Gmail Pub/Sub push and the Polar webhook. Sign-in lives
    on the app host now; the standalone /onboard flow was retired."""
    return f"""\
{site.API_HOST} {{
\thandle {site.POLAR_WEBHOOK_PATH} {{
\t\treverse_proxy 127.0.0.1:{site.BILLING_WEBHOOK_PORT}
\t}}
{co_tenant_handles()}\
\t# The catch-all keeps the Gmail Pub/Sub push (POST /) on the webhook. Serving
\t# a landing page from this site root would require repointing the push
\t# subscription off "/" first.
\thandle {{
\t\treverse_proxy 127.0.0.1:{site.GMAIL_PUSH_PORT}
\t}}
}}"""


def app_block():
    """The product host: web UI on every path, plus the Polar webhook so the
    endpoint can be moved here without touching the Polar dashboard twice."""
    return f"""\
{site.APP_HOST} {{
\thandle {site.POLAR_WEBHOOK_PATH} {{
\t\treverse_proxy 127.0.0.1:{site.BILLING_WEBHOOK_PORT}
\t}}
{co_tenant_handles()}\
\thandle {{
\t\treverse_proxy 127.0.0.1:{site.WEB_PORT}
\t}}
}}"""


def alias_blocks():
    return [f"{host} {{\n\tredir https://{site.APP_HOST}{{uri}} permanent\n}}"
            for host in site.ALIAS_HOSTS]


def render():
    blocks = [api_block(), app_block(), *alias_blocks()]
    return HEADER + "\n" + "\n\n".join(blocks) + "\n"


if __name__ == "__main__":
    sys.stdout.write(render())
