"""Render the measured image's file list from what the enclave actually loads.

`flake.nix` used to copy the repository into the image behind a filter written
as "every .py that is not a test, plus .css, minus five directory names". That
filter is wrong in both directions at once.

Too much: it shipped the co-signer's key derivation and request policy, the
egress proxy, the billing webhook and poller, the masking evaluator and the
by-hand tools into an image that starts none of them. Every one of those is code
an attacker with execution inside the enclave can call, and every dependency
bump touching them changes the measurement for a path that does not run.

Too little, and worse: it shipped no data files at all, because none end in .py
or .css. The image has no `default_voice.md`, so the first account without its
own profile asserts; no `inference_allowlist.json`, so no confidential provider
can be authorized; and no brand assets, so every page 500s on its own icon. The
filter was a description of the tree rather than an answer about the program.

So the list is derived instead. `tools/reachability.py` walks imports from the
entry points `flake.nix` itself starts, and that set of modules is the list.
Adding a module to the image now means importing it from something that runs.

    python -m deploy.render_image_manifest            # rewrite the file
    python -m deploy.render_image_manifest --check    # exit 1 if it is stale

`tests/test_image_manifest.py` runs the check, so a new import that pulls a new
module into the enclave fails there rather than in a CVM.

Data files cannot be derived -- nothing in an import graph says a module reads a
JSON file beside it -- so they are listed here, each with the module that reads
it, and the renderer asserts every one exists.
"""

import sys

from backend import paths
from tools import reachability

MANIFEST_FILE = paths.REPO_ROOT / "deploy" / "phala" / "image_files.nix"

# Path -> the module that reads it. Asserted to exist at render time, because a
# renamed asset that silently drops out of the image is the failure this whole
# module is about.
DATA_FILES = {
    "backend/drafting/default_voice.md": "backend.drafting.voice_dna",
    "backend/integrations/inference_allowlist.json":
        "backend.integrations.inference_attestation",
    "frontend/static/app.css": "frontend.web_server",
    "frontend/static/favicon.ico": "frontend.web_server",
    "frontend/static/favicon-32.png": "frontend.web_server",
    "frontend/static/icon-512.png": "frontend.web_server",
    "frontend/static/apple-touch-icon.png": "frontend.web_server",
    "frontend/static/mark.png": "frontend.web_server",
}

# Modules nothing starts, that still have to be in the enclave because the data
# they work on is only there. An import graph cannot find these -- that is the
# point of a command -- so each is written down with the reason it ships.
EXTRA_MODULES = {
    "backend.accounts.whois":
        "the only mapping from an opaque handle back to a person lives in the "
        "manifest, and the manifest is here",
    "backend.custody.rotate":
        "rotation rewrites every record onto a new co-signer key, and the "
        "records are here; a rotation tool on the box would have nothing to "
        "rewrite",
}

HEADER = """# Every file the measured enclave image carries.
#
# Generated by deploy/render_image_manifest.py from the modules reachable from
# the entry points in flake.nix -- do not edit. A module belongs here because
# something that starts imports it; add the import, then re-render.
#
#   python -m deploy.render_image_manifest
#
# tests/test_image_manifest.py fails if this file stops matching the tree.
"""


def module_files():
    """The source files the enclave's entry points reach, repo-relative."""
    graph = reachability.Graph()
    for name in EXTRA_MODULES:
        assert name in graph.modules, (
            f"{name} is listed as an enclave command but is not a module")
    reachable = graph.reachable_modules(
        reachability.enclave_roots() | set(EXTRA_MODULES))
    out = set()
    for name in reachable:
        mod = graph.modules[name]
        out.add(str(mod.path.relative_to(paths.REPO_ROOT)))
    assert out, "the enclave reaches no modules; the entry points did not parse"
    return out


def data_files():
    for rel, reader in sorted(DATA_FILES.items()):
        assert (paths.REPO_ROOT / rel).is_file(), (
            f"{rel} is listed as an image data file for {reader} but is not "
            f"there; a renamed asset drops out of the image silently otherwise"
        )
    return set(DATA_FILES)


def render_paths():
    """The image's file list, sorted. The one answer both the renderer and the
    tests read, so a test cannot pass against a list the image does not use."""
    return sorted(module_files() | data_files())


def render():
    body = "".join(f'  "{rel}"\n' for rel in render_paths())
    return f"{HEADER}[\n{body}]\n"


def main(argv):
    rendered = render()
    if "--check" in argv:
        current = MANIFEST_FILE.read_text() if MANIFEST_FILE.exists() else ""
        if rendered != current:
            print(f"{MANIFEST_FILE} is stale; run "
                  "`python -m deploy.render_image_manifest`", file=sys.stderr)
            return 1
        return 0
    MANIFEST_FILE.write_text(rendered)
    print(f"wrote {MANIFEST_FILE} ({rendered.count(chr(10)) - HEADER.count(chr(10)) - 2} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
